
# Task 01 Mineria de Datos
## Ernesto Camacho Arroyave

In [4]:
import pandas as pd
from numpy.core.numeric import Inf

**Desarrollo de los Items del trabajo de analisis solicitado.**

# Desarrollo

**1) Cargar en Jupyter el archivo suministrado: covid_global.csv**

In [5]:
covid_gobal_dataframe= pd.read_csv("https://raw.githubusercontent.com/ErnestoCamachoA9805/MIND/main/Task01/covid_global.csv")
#covid_gobal_dataframe= covid_gobal_dataframe.sort_values('Country')
covid_gobal_dataframe.head()

              Country        Lat       Long  ...  01/17/22  01/18/22  status
0           Venezuela   6.423800 -66.589700  ...         0         0       R
1              Kosovo  42.602636  20.902977  ...      2994      2995       D
2            Slovenia  46.151200  14.995500  ...      5705      5715       D
3  West Bank and Gaza  31.952200  35.233200  ...         0         0       R
4              Canada   0.000000   0.000000  ...         0         0       D

[5 rows x 732 columns]

**2) Calcular y mostrar la cantidad de pacientes recuperados y muertos en cada continente.**
- Para este ejercicio los paises se van a organizar de acuerdo a un csv encontrado en internet. (https://github.com/dbouquin/IS_608/blob/master/NanosatDB_munging/Countries-Continents.csv)
- Esto significa que los datos que no son de paises son eliminados

In [6]:
continent_dataframe= pd.read_csv("https://raw.githubusercontent.com/ErnestoCamachoA9805/MIND/main/Task01/Continents.csv")
dataf= covid_gobal_dataframe.merge(continent_dataframe, on="Country")
dataf= dataf.sort_values(["Continent","Country"])
continent_dataframe= None
## 
dir= {"Africa":[0,0],"Asia":[0,0],"Europe":[0,0],"North America":[0,0],"Oceania":[0,0],"South America":[0,0],}
for index, row in dataf.iterrows():
  if row["status"]== "D":
    dir[row["Continent"]][0]+= row["12/31/21"] + row["12/31/20"]
  elif row["status"]== "R":
    dir[row["Continent"]][1]+= row["12/31/21"] + row["12/31/20"]
for key in dir.keys():
  print("El numero de muertos en el contiente " + key + " es: " + str(dir[key][0]))
  print("El numero de recuperaciones en el contiente " + key + " es: " + str(dir[key][1]))
  print()

El numero de muertos en el contiente Africa es: 287877
El numero de recuperaciones en el contiente Africa es: 2231536

El numero de muertos en el contiente Asia es: 1530169
El numero de recuperaciones en el contiente Asia es: 18437103

El numero de muertos en el contiente Europe es: 1694403
El numero de recuperaciones en el contiente Europe es: 8690888

El numero de muertos en el contiente North America es: 1735736
El numero de recuperaciones en el contiente North America es: 2312466

El numero de muertos en el contiente Oceania es: 4533
El numero de recuperaciones en el contiente Oceania es: 25364

El numero de muertos en el contiente South America es: 1610140
El numero de recuperaciones en el contiente South America es: 11843822

- Los resultados salen de la suma de 2 fechas que considero reportan de manera completa la cantidad de personas por año, esta fecha es el 31 de diciembre del año

**3) Indicar el país con el mayor crecimiento en la cantidad de recuperados y muertos durante el año 2022.**

- Un detalle de los datos es que no hay datos de recuperaciones en el 2022 por lo que se hara el calculo solo las muertes. 
- Los datos de poblacion de cada pais son recuperados del csv de la pagina(https://worldpopulationreview.com/)

In [7]:
pop_data= pd.read_csv("https://raw.githubusercontent.com/ErnestoCamachoA9805/MIND/main/Task01/world_population.csv")
pop_data= pop_data[['name','pop2021']]
pop_data= pop_data.rename(columns={'name': 'Country'})
dataf= dataf.merge(pop_data, on="Country")

In [8]:
temporalDf= dataf[dataf["status"]!= "R"]
country= ''
value= 0
for index, row in temporalDf.iterrows():
  tasa= (row["01/18/22"] - row["01/01/22"])/row["pop2021"]
  if tasa >= value:
    country= row["Country"]
print("El pais con mayor crecimiento en muertos del 2022 es: " + country)

El pais con mayor crecimiento en muertos del 2022 es: Venezuela

- Para determinar el valor tome el valor de la fecha mas reciente, menos el valor del primero de enero, dividio la poblacion del pais.

**4) Indicar el país con el menor crecimiento en la cantidad de recuperados y muertos durante el año 2021.**

In [9]:
countryR= ''
countryD= ''
valueR= Inf
valueD= Inf
for index, row in dataf.iterrows():
  tasa= (row["12/31/21"] - row["01/01/21"])/row["pop2021"]
  if row["status"] == "R":
    if tasa <= valueR:
      #print(row["Country"])
      countryR= row["Country"]
  else:
    if tasa <= valueD:
      countryD= row["Country"]
print("El pais con menor crecimiento en recuperados del 2021 es: " + countryR)
print("El pais con menor crecimiento en muertos del 2021 es: " + countryD)

El pais con menor crecimiento en recuperados del 2021 es: Venezuela
El pais con menor crecimiento en muertos del 2021 es: Venezuela

- La formula es similar a la del punto 3, sin embargo para esta si inclui los datos y el calculo del numero de recuperados

**5) Indicar por continente el país con mejor tasa de sobrevivientes para cada año: 2020, 2021 y 2022.**
- Para este punto tomaremos la poblacion de infectados (recuperados mas muertos) como poblacion total.
-Para el calculo de la tasa de recuperacion haremos una regla de 3 tomando como valores a la poblacion de infectados y al numero de recuperados, en 2 puntos en el tiempo, en la primera fecha y en la ultima.

   Country      Lat     Long  01/22/20  ...  01/18/22  status  Continent    pop2021
0  Algeria  28.0339   1.6596         0  ...      6435       D     Africa  44616.624
1  Algeria  28.0339   1.6596         0  ...         0       R     Africa  44616.624
2   Angola -11.2027  17.8739         0  ...      1870       D     Africa  33933.610
3   Angola -11.2027  17.8739         0  ...         0       R     Africa  33933.610
4    Benin   9.3077   2.3158         0  ...         0       R     Africa  12451.040

[5 rows x 734 columns]

**6) Realice un diagrama de barras (barplot) que permita visualizar la cantidad de pacientes recuperados por año para los 10 primeros paises en tasa de contagio.**

**7) Realice un diagrama de barras (barplot) que permita visualizar la cantidad de pacientes fallecidos por
año para los 10 primeros paises en tasa de contagio**

**8) Realice un diagrama de caja (boxplot) con las cifras de los tres años para Colombia, para pacientes
recuperados y muertos. ¿Cuál es su interpretación a lo visualizado en el gráfico?**

**9) Para cada una de las variables muestre el consolidado de la siguiente información: valor mínimo,
primer cuartil, promedio, tercer cuartil y valor máximo. Recuerde se requiere para cada variable
numérica.**

In [12]:
dataf[3:730].describe()

              Lat        Long  ...       01/18/22       pop2021
count  499.000000  499.000000  ...     502.000000  5.020000e+02
mean    19.352769   23.380150  ...    8549.862550  2.257739e+05
std     25.217341   76.248702  ...   43164.501783  4.918294e+05
min    -51.796300 -178.116500  ...       0.000000  1.816900e+01
25%      4.715658  -42.604300  ...       0.000000  4.479964e+03
50%     19.856270   23.881300  ...       0.000000  1.824986e+04
75%     39.474450   88.092400  ...     745.750000  6.542618e+04
max     71.706900  178.065000  ...  621803.000000  1.444216e+06

[8 rows x 731 columns]